# gradle/libs.versions.toml
[versions]
kotlin = "2.3.0"
arrow = "2.2.1.1"
ksp = "2.3.3"
kotlinpoet = "2.2.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

[libraries]
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
hnau-kotlin = { module = "com.github.hnau256.common-kotlin:common-kotlin", version = "1.7.0" }
#hnau-gen-kt = { module = "com.github.hnau256:common-gen-kt", version = "1.0.0" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet-main = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }